name: Stracciatella fork Github runner configuration
on: push

jobs:
  Build-with-gcc:
    name: Ubuntu Latest, GCC 14
    runs-on: ubuntu-24.04
    steps:
      - name: Install Nina
        shell: bash
        run: |
          sudo apt-get install ninja-build -y
      - name: Install SDL2
        shell: bash
        run: |
          sudo apt-get install libsdl2-dev -y
      - name: Choose GCC 14
        shell: bash
        run: |
          update-alternatives --query g++
          sudo update-alternatives --set /usr/bin/g++14
      - uses: actions/checkout@v4
      - name: Configure CMake
        shell: bash
        run: |
          mkdir /tmp/build
          cmake -DCMAKE_UNITY_BUILD:bool=ON -DENABLE_PCH:bool=ON -G "Ninja Multi-Config" -S . -B ./tmp/build
      - name: Build
        shell: bash
        run: |
          cmake --build /tmp/build --config RelWithDebInfo

