name: Stracciatella fork Github runner configuration
on: push

jobs:
  Build-with-gcc:
    name: Ubuntu Latest, GCC 14
    runs-on: ubuntu-24.04
    steps:
      - name: Install Ninja
        shell: bash
        run: |
          sudo apt-get install ninja-build -y
      - name: Install SDL2
        run: sudo apt-get install libsdl2-dev -y
      - name: Install FLTK
        run: sudo apt install fltk1.3-dev -y
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure CMake
        shell: bash
        run: |
          mkdir /tmp/build
          cmake -DCMAKE_CXX_COMPILER=g++-14 -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_UNITY_BUILD:bool=ON -DENABLE_PCH:bool=ON -G "Ninja Multi-Config" -S . -B /tmp/build
      - name: Build
        run: cmake --build /tmp/build --config RelWithDebInfo

  Build-with-clang:
    name: Ubuntu Latest, Clang 18
    runs-on: ubuntu-24.04
    steps:
      - name: Install Ninja
        run: sudo apt-get install ninja-build -y
      - name: Install SDL2
        run: sudo apt-get install libsdl2-dev -y
      - uses: actions/checkout@v4
      - name: Configure CMake
        shell: bash
        run: |
          mkdir /tmp/build
          cmake -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_C_COMPILER=clang-18 -DCMAKE_UNITY_BUILD:bool=ON -DENABLE_PCH:bool=ON -G "Ninja Multi-Config" -S . -B /tmp/build
      - name: Build
        run: cmake --build /tmp/build --config RelWithDebInfo
      - name: Run unit tests
        shell: bash
        run: |
          cd /tmp/build/RelWithDebInfo
          ./ja2 -unittests