name: Triggered by push
on: push

jobs:
  Build-with-gcc:
    name: Ubuntu Latest, GCC 14, Ninja
    runs-on: ubuntu-24.04
    steps:
      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - name: Install SDL2 and FLTK
        run: sudo apt-get install libsdl2-dev libfltk1.3-dev

      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          clean: false

      - name: Configure CMake
        run: >
          mkdir /tmp/build

          cmake
          -DCMAKE_CXX_COMPILER=g++-14
          -DCMAKE_C_COMPILER=gcc-14
          -DCMAKE_UNITY_BUILD:bool=ON
          -DENABLE_PCH:bool=ON
          -DWITH_MAGICENUM:bool=OFF
          -G "Ninja Multi-Config"
          -S . -B /tmp/build

      - name: Build
        run: cmake --build /tmp/build --config RelWithDebInfo

  Build-with-clang:
    name: Ubuntu Latest, Clang 18, Make
    runs-on: ubuntu-24.04
    steps:
      - name: Install SDL2, Lua 5.3 and gtest
        run: sudo apt-get install libsdl2-dev liblua5.3-dev libgtest-dev

      - name: Checkout
        uses: actions/checkout@v4
        with: [ show-progress: false, clean: false ]

      - name: Configure CMake
        run: |
          mkdir /tmp/build
          cmake -DBUILD_LAUNCHER:bool=OFF -DLOCAL_LUA_LIB:bool=OFF -DLOCAL_GTEST_LIB:bool=OFF -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_C_COMPILER=clang-18 -DCMAKE_UNITY_BUILD:bool=ON -DENABLE_PCH:bool=ON -S . -B /tmp/build

      - name: Build
        run: |
          cmake --build /tmp/build -j 4
          echo -n "Executable size: " && du -b /tmp/build/ja2

      - name: Run unit tests
        working-directory: /tmp/build
        run: ./ja2 -unittests

  Tar version:
    name: Tar
    runs-on: ubuntu-20.04
    steps:
      -name: Print tar version
      -run: tar --version