name: Triggered by push
on: push

jobs:
  Build-with-gcc:
    name: Ubuntu Latest, GCC 14, Ninja
    runs-on: ubuntu-24.04
    steps:
      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - name: Install dependencies
        run: sudo apt-get install libsdl2-dev libfltk1.3-dev liblua5.3-dev libgtest-dev

      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          clean: false

      - name: Configure CMake
        run: >
          mkdir /tmp/build

          cmake
          -DCMAKE_CXX_COMPILER=g++-14
          -DCMAKE_C_COMPILER=gcc-14
          -DCMAKE_CXX_FLAGS=-pipe
          -DCMAKE_UNITY_BUILD:bool=ON
          -DENABLE_PCH:bool=ON
          -DLOCAL_GTEST_LIB:bool=OFF
          -DLOCAL_LUA_LIB:bool=OFF
          -S . -B /tmp/build
          -G "Ninja Multi-Config"

      - name: Build
        run: cmake --build /tmp/build --config RelWithDebInfo

  Build-with-clang:
    name: Ubuntu Latest, Clang 18, Make
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install libsdl2-dev liblua5.3-dev libgtest-dev

      - name: Checkout
        uses: actions/checkout@v4
        with: { show-progress: false, clean: false }

      - name: Configure CMake
        run: >
          mkdir /tmp/build

          cmake
          -DCMAKE_CXX_COMPILER=clang++-18
          -DCMAKE_C_COMPILER=clang-18
          -DCMAKE_CXX_FLAGS=-pipe
          -DCMAKE_BUILD_TYPE=MinSizeRel
          -DBUILD_LAUNCHER:bool=OFF
          -DWITH_MAGICENUM:bool=OFF
          -DLOCAL_GTEST_LIB:bool=OFF
          -DLOCAL_LUA_LIB:bool=OFF
          -DCMAKE_UNITY_BUILD:bool=ON
          -DENABLE_PCH:bool=ON
          -S . -B /tmp/build

      - name: Build
        run: |
          cmake --build /tmp/build -j 4
          echo -n "Executable size: " && du -b /tmp/build/ja2

      - name: Run unit tests
        working-directory: /tmp/build
        run: ./ja2 -unittests
