name: Windows runner, manually triggered
on: workflow_dispatch

jobs:
  Build-with-msvc:
    name: Visual Studio 
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: vcpkg install sdl2 lua gtest

      - name: Checkout
        uses: actions/checkout@v4
        with: { show-progress: false, clean: false }

      - name: Configure CMake
        run: >
          mkdir %TEMP%\build

          cmake
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DCMAKE_UNITY_BUILD:bool=ON
          -DENABLE_PCH:bool=ON
          -DLOCAL_GTEST_LIB:bool=OFF
          -DLOCAL_LUA_LIB:bool=OFF
          -S . -B %TEMP%\build

      - name: Build
        run: cmake --build %TEMP%\build

      - name: Run unit tests
        working-directory: %TEMP%\build
        run: ./ja2 -unittests

